title: Lawton Hall

collections:
  works:
    output: true
    permalink: /works/:name/

  practice:
    output: true
    permalink: /practice/:name/

defaults:
  - scope:
      path: "talks"
    values:
      layout: default
      theme: pink
      noindex: true
      sitemap: false
